services:
  database:
    container_name: 'postgres'
    image: 'postgres:17.4-alpine'
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MAX_CONNECTIONS=200
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./deploy/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 2s

  prometheus:
    container_name: 'prometheus'
    image: prom/prometheus:v3.2.1
    ports:
      - 9090:9090
    networks:
      - default
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml

  grafana: # login: admin, password: admin
    container_name: 'grafana'
    image: grafana/grafana:11.6.0
    networks:
      - default
    ports:
      - 3333:3000
    volumes:
      - ./graphana/datasources:/etc/grafana/provisioning/datasources
      - ./graphana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana

  backend:
    container_name: 'backend'
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=database
    build: ./backend
    volumes:
      - ./certs:/etc/ssl
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    command: [ "sh", "-c", "poetry run alembic upgrade head && poetry run python -m app" ]

  nginx:
    container_name: 'nginx'
    image: nginx:1.27.4-alpine
    ports:
      - "80:80" # HTTP
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf # Dev Nginx configuration
      - ./certs:/etc/ssl # SSL certificates
    depends_on:
      - backend

  pgbackups:
    image: prodrigestivill/postgres-backup-local:17-alpine-437f2e9
    restart: always
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    depends_on:
      - database
    networks:
      - default
    volumes:
      - ./backups:/backups

networks:
  default:
volumes:
  data:
  prometheus-data:
  grafana-data: