{
 "title": "System",
 "description": "Basic system monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_mem_used_gb / system_mem_total_gb) * 100"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_ms_bucket[5m])) by (le)) # p99",
     "legendFormat": "99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_ms_bucket[5m])) by (le)) # p95\n",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_latency_ms_bucket[5m])) by (le)) # p90\n",
     "legendFormat": "90p"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_mem_used_gb", "legendFormat": "Memory usage" }
   ]
  },
  { "title": "Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Request by status_code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(responses_total[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(system_mem_used_gb / system_mem_total_gb) * 100",
     "legendFormat": "Memory usage"
    }
   ]
  }
 ]
}